import React from 'react';
import { AlertTriangle, BookOpen, ShieldCheck, Scale, Landmark, MessageSquare } from 'lucide-react';
import SEOManager from './calculators/shared/SEOManager';

export default function DisclaimerPage() {
  const origin = typeof window !== 'undefined' && window.location.origin ? window.location.origin : '';

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8 space-y-10 animate-fade-in">
      <SEOManager
        title="Financial Disclaimer | Sequenxe Educational Platform"
        description="Important legal disclaimer for Sequenxe: Content and calculations are for educational and informational purposes only and do not constitute financial, tax, or legal advice."
        canonicalUrl={`${origin}/disclaimer`}
        breadcrumbs={[
          { name: 'Home', url: `${origin}/` },
          { name: 'Disclaimer', url: `${origin}/disclaimer` }
        ]}
      />

      {/* Header */}
      <div className="space-y-3 border-b border-border-custom pb-6">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 text-amber-700 text-xs font-bold font-mono">
          <AlertTriangle className="h-4 w-4 text-amber-600" />
          <span>Important Notice</span>
        </div>
        <h1 className="text-3xl font-extrabold tracking-tight text-text-primary sm:text-4xl font-display">
          Financial & Legal Disclaimer
        </h1>
        <p className="text-xs sm:text-sm text-text-secondary">
          Last Updated: January 2026 • Sequenxe Educational Platform
        </p>
      </div>

      <div className="space-y-8 bg-white p-6 sm:p-10 rounded-2xl border border-border-custom shadow-2xs text-xs sm:text-sm text-text-primary leading-relaxed">
        
        {/* Highlighted Warning Box */}
        <div className="bg-amber-500/10 border border-amber-500/30 p-5 rounded-2xl space-y-2 text-amber-900">
          <div className="flex items-center gap-2 font-bold text-sm font-display text-amber-900">
            <AlertTriangle className="h-5 w-5 text-amber-600 shrink-0" />
            <span>Summary Disclaimer</span>
          </div>
          <p className="text-xs sm:text-sm leading-relaxed text-amber-950 font-medium">
            All tools, mathematical formulas, tax relief estimates, loan calculators, and articles on Sequenxe are published strictly for educational and informational purposes only. They do not constitute certified financial, tax, legal, accounting, or investment advice.
          </p>
        </div>

        {/* 1. Educational Purpose Only */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-text-primary font-display flex items-center gap-2">
            <BookOpen className="h-5 w-5 text-primary" />
            <span>1. Educational & Informational Purposes Only</span>
          </h2>
          <p className="text-text-secondary leading-relaxed">
            Sequenxe provides interactive financial tools designed to help users understand general statutory deduction formulas (such as LHDN PCB tax tables, KWSP EPF contributions, PERKESO SOCSO, and Bank Negara loan amortization guidelines).
          </p>
          <p className="text-text-secondary leading-relaxed">
            The results generated by our calculators are mathematical approximations based on user inputs. They should not be used as official tax filings, binding loan commitments, or formal financial audits.
          </p>
        </section>

        {/* 2. No Licensed Professional Relationship */}
        <section className="space-y-3 border-t border-border-custom/60 pt-6">
          <h2 className="text-lg font-bold text-text-primary font-display flex items-center gap-2">
            <Scale className="h-5 w-5 text-primary" />
            <span>2. No Financial, Legal, or Tax Advice</span>
          </h2>
          <p className="text-text-secondary leading-relaxed">
            Your use of Sequenxe does not create a licensed advisor-client or fiduciary relationship. Sequenxe is not a licensed financial planner (FPC), tax agent registered under LHDN, or licensed mortgage broker under Bank Negara Malaysia.
          </p>
        </section>

        {/* 3. Verification with Official Authorities */}
        <section className="space-y-3 border-t border-border-custom/60 pt-6">
          <h2 className="text-lg font-bold text-text-primary font-display flex items-center gap-2">
            <Landmark className="h-5 w-5 text-emerald-600" />
            <span>3. Verification with Official Authorities</span>
          </h2>
          <p className="text-text-secondary leading-relaxed font-semibold text-text-primary">
            Users are strongly advised to verify all calculation outputs with official Malaysian government bodies or qualified licensed professionals before taking financial action:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
            <div className="bg-bg-custom/40 p-3.5 rounded-xl border border-border-custom/70">
              <div className="font-bold text-xs text-text-primary">LHDN (Lembaga Hasil Dalam Negeri)</div>
              <p className="text-[11px] text-text-secondary">For official income tax e-Filing, chargeable income verification, and gazetted tax relief claims.</p>
            </div>
            <div className="bg-bg-custom/40 p-3.5 rounded-xl border border-border-custom/70">
              <div className="font-bold text-xs text-text-primary">KWSP (EPF)</div>
              <p className="text-[11px] text-text-secondary">For official retirement savings statements, statutory rate options, and Akaun 1/2/3 withdrawal rules.</p>
            </div>
            <div className="bg-bg-custom/40 p-3.5 rounded-xl border border-border-custom/70">
              <div className="font-bold text-xs text-text-primary">PERKESO & SIP (SOCSO / EIS)</div>
              <p className="text-[11px] text-text-secondary">For statutory employment injury and employment insurance benefits.</p>
            </div>
            <div className="bg-bg-custom/40 p-3.5 rounded-xl border border-border-custom/70">
              <div className="font-bold text-xs text-text-primary">Bank Negara Malaysia & Commercial Banks</div>
              <p className="text-[11px] text-text-secondary">For official home mortgage approval, Debt Service Ratio (DSR) caps, and actual interest rate quotes.</p>
            </div>
          </div>
        </section>

        {/* 4. Limitation of Liability */}
        <section className="space-y-3 border-t border-border-custom/60 pt-6">
          <h2 className="text-lg font-bold text-text-primary font-display flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-primary" />
            <span>4. Limitation of Liability</span>
          </h2>
          <p className="text-text-secondary leading-relaxed">
            While we strive for absolute accuracy in our formulas and update our tools annually for Year of Assessment 2026, Sequenxe and its operators shall not be held liable for any financial decisions, tax penalties, loan rejections, errors, or omissions resulting from reliance on the information or tools provided.
          </p>
        </section>

        {/* Contact */}
        <section className="space-y-3 border-t border-border-custom/60 pt-6">
          <h2 className="text-lg font-bold text-text-primary font-display flex items-center gap-2">
            <MessageSquare className="h-5 w-5 text-primary" />
            <span>5. Contact Us</span>
          </h2>
          <p className="text-text-secondary leading-relaxed">
            If you notice a mathematical discrepancy or have questions regarding our calculations, please reach out to us using our online Contact Form.
          </p>
        </section>

      </div>
    </div>
  );
}
